spring:
  main:
    banner-mode: 'off'
  datasource:
    url: jdbc:mysql://localhost:3306/inspire_me_db?useSSL=false
    username: springuser
    password: ThePassword
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    baselineOnMigrate: true
#  mvc:
#    view:
#      prefix: webapp/resources/WEB-INF/view/
#      suffix: .jsp
  messages:
    basename: validation

logging:
  level:
    org:
      springframework: TRACE
    com: TRACE
---
spring:
  profiles: h2
  datasource:
    driver-class-name: org.h2.Driver
    url:
  h2:
    console:
      enabled: true
      path: /console/