INSERT INTO USER (USER_NAME, EMAIL_ADDRESS, PASSWORD, USER_TYPE, DATE_USER_CREATED) VALUES ('adminus', 'admin@test.com', 'mypass', 0, NOW());
INSERT INTO USER (USER_NAME, EMAIL_ADDRESS, PASSWORD, USER_TYPE, DATE_USER_CREATED) VALUES ('visitor1', 'visi1@test.com', 'visipass', 1, NOW());
INSERT INTO USER (USER_NAME, EMAIL_ADDRESS, PASSWORD, USER_TYPE, DATE_USER_CREATED) VALUES ('visitor2', 'visi2@test.com', 'vispassw', 1, NOW());

INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Personal Development');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Mental Health');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Psychology');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Spirituality');
