INSERT INTO USER (USER_NAME, USER_TYPE, DATE_USER_CREATED, PASSWORD) VALUES ('adminus', 0, NOW(), '12345');
INSERT INTO USER (USER_NAME, USER_TYPE, DATE_USER_CREATED, PASSWORD) VALUES ('visitor1', 1, NOW(), '12345');
INSERT INTO USER (USER_NAME, USER_TYPE, DATE_USER_CREATED, PASSWORD) VALUES ('visitor2', 1, NOW(), '12345');

INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Personal Development');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Mental Health');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Psychology');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Spirituality');
