INSERT INTO USER (DATE_USER_CREATED, USER_TYPE) VALUES (NOW(), 0);
INSERT INTO USER (DATE_USER_CREATED, USER_TYPE) VALUES (NOW(), 1);
INSERT INTO USER (DATE_USER_CREATED, USER_TYPE) VALUES (NOW(), 1);

INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ("Personal Development");
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ("Mental Health");
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ("Psychology");
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ("Spirituality");
