INSERT INTO USER (USER_NAME, USER_TYPE, DATE_USER_CREATED) VALUES ('adminus', 0, NOW());
INSERT INTO USER (USER_NAME, USER_TYPE, DATE_USER_CREATED) VALUES ('visitor1', 1, NOW());
INSERT INTO USER (USER_NAME, USER_TYPE, DATE_USER_CREATED) VALUES ('visitor2', 1, NOW());

INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Personal Development');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Mental Health');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Psychology');
INSERT INTO CATEGORY (CATEGORY_NAME) VALUES ('Spirituality');
