INSERT INTO ARTICLE (ARTICLE_TITLE, ARTICLE_TEXT, IMAGE_URL, DATE_ARTICLE_PUBLISHED, ARTICLE_PUBLISHED_BY_USER_ID, CATEGORY_CATEGORY_ID) VALUES (
'Article title 1',
'Lorem ipsum dolor sit amet consectetur adipiscing elit facilisi tempor posuere sapien, nunc cum proin et ultricies ultrices tortor maecenas nisl consequat eleifend, nascetur lobortis donec ad sed blandit curae augue vulputate torquent. Id sapien quis nisl neque cubilia euismod cursus in arcu, nibh potenti nam pharetra ornare accumsan augue sociosqu maecenas, mi rutrum metus purus tellus justo sagittis ut. Viverra hac vel duis varius aliquam cursus convallis est mi odio, posuere aenean per integer dignissim inceptos gravida pellentesque neque, rutrum nisl accumsan habitant vulputate turpis enim eros bibendum. Vulputate tellus quis nisl cum varius sollicitudin ut ornare malesuada, ullamcorper feugiat arcu proin dapibus est natoque vitae, cras enim viverra praesent massa pharetra taciti fusce. Nulla praesent eget scelerisque laoreet aptent purus luctus vel duis pellentesque cursus feugiat tristique bibendum, faucibus pulvinar ante augue accumsan iaculis sociosqu facilisi ornare dictumst odio varius. Gravida facilisis vestibulum rutrum condimentum ad vitae sapien aenean id, mus diam fermentum nisl accumsan tincidunt enim pharetra malesuada, tristique semper scelerisque morbi placerat suspendisse dui dictumst.',
'https://bit.ly/2tC5qX3', NOW(), 1, 1);
INSERT INTO ARTICLE (ARTICLE_TITLE, ARTICLE_TEXT, IMAGE_URL, DATE_ARTICLE_PUBLISHED, ARTICLE_PUBLISHED_BY_USER_ID, CATEGORY_CATEGORY_ID) VALUES ('Article title 2', 'Another sample article', 'https://bit.ly/2BHiSO3', NOW(), 1, 2);
INSERT INTO ARTICLE (ARTICLE_TITLE, ARTICLE_TEXT, IMAGE_URL, DATE_ARTICLE_PUBLISHED, ARTICLE_PUBLISHED_BY_USER_ID, CATEGORY_CATEGORY_ID) VALUES ('Article title 3', 'Somee sample article', 'https://bit.ly/2tC5qX3', NOW(), 1, 3);
INSERT INTO ARTICLE (ARTICLE_TITLE, ARTICLE_TEXT, IMAGE_URL, DATE_ARTICLE_PUBLISHED, ARTICLE_PUBLISHED_BY_USER_ID, CATEGORY_CATEGORY_ID) VALUES ('Article title 4', 'Anothere sample article', 'https://bit.ly/2BHiSO3', NOW(), 1, 4);
INSERT INTO ARTICLE (ARTICLE_TITLE, ARTICLE_TEXT, IMAGE_URL, DATE_ARTICLE_PUBLISHED, ARTICLE_PUBLISHED_BY_USER_ID, CATEGORY_CATEGORY_ID) VALUES ('Article title 5', 'Some samplee article', 'https://bit.ly/2tC5qX3', NOW(), 1, 2);
INSERT INTO ARTICLE (ARTICLE_TITLE, ARTICLE_TEXT, IMAGE_URL, DATE_ARTICLE_PUBLISHED, ARTICLE_PUBLISHED_BY_USER_ID, CATEGORY_CATEGORY_ID) VALUES ('Article title 6', 'Another samplee article', 'https://bit.ly/2BHiSO3', NOW(), 1, 3);
INSERT INTO ARTICLE (ARTICLE_TITLE, ARTICLE_TEXT, IMAGE_URL, DATE_ARTICLE_PUBLISHED, ARTICLE_PUBLISHED_BY_USER_ID, CATEGORY_CATEGORY_ID) VALUES ('Article title 7', 'Another sample articlee', 'https://bit.ly/2BHiSO3', NOW(), 1, 4);
INSERT INTO ARTICLE (ARTICLE_TITLE, ARTICLE_TEXT, IMAGE_URL, DATE_ARTICLE_PUBLISHED, ARTICLE_PUBLISHED_BY_USER_ID, CATEGORY_CATEGORY_ID) VALUES ('Article title 8', 'Some sample articlee', 'https://bit.ly/2tC5qX3', NOW(), 1, 2);
INSERT INTO ARTICLE (ARTICLE_TITLE, ARTICLE_TEXT, IMAGE_URL, DATE_ARTICLE_PUBLISHED, ARTICLE_PUBLISHED_BY_USER_ID, CATEGORY_CATEGORY_ID) VALUES ('Article title 9', 'Another sample articleme', 'https://bit.ly/2BHiSO3', NOW(), 1, 2);