INSERT INTO ARTICLE (ARTICLE_TITLE, ARTICLE_TEXT, IMAGE_URL, DATE_ARTICLE_PUBLISHED, ARTICLE_PUBLISHED_BY_USER_ID, CATEGORY_CATEGORY_ID) VALUES (
'Lorem ipsum dolor sit amet, consectetur adipiscing elit in tempor lorem sed orn',
'Lorem ipsum dolor sit amet consectetur adipiscing elit facilisi tempor posuere sapien, nunc cum proin et ultricies ultrices tortor maecenas nisl consequat eleifend, nascetur lobortis donec ad sed blandit curae augue vulputate torquent. Id sapien quis nisl neque cubilia euismod cursus in arcu, nibh potenti nam pharetra ornare accumsan augue sociosqu maecenas, mi rutrum metus purus tellus justo sagittis ut. Viverra hac vel duis varius aliquam cursus convallis est mi odio, posuere aenean per integer dignissim inceptos gravida pellentesque neque, rutrum nisl accumsan habitant vulputate turpis enim eros bibendum. Vulputate tellus quis nisl cum varius sollicitudin ut ornare malesuada, ullamcorper feugiat arcu proin dapibus est natoque vitae, cras enim viverra praesent massa pharetra taciti fusce. Nulla praesent eget scelerisque laoreet aptent purus luctus vel duis pellentesque cursus feugiat tristique bibendum, faucibus pulvinar ante augue accumsan iaculis sociosqu facilisi ornare dictumst odio varius. Gravida facilisis vestibulum rutrum condimentum ad vitae sapien aenean id, mus diam fermentum nisl accumsan tincidunt enim pharetra malesuada, tristique semper scelerisque morbi placerat suspendisse dui dictumst.',
'https://bit.ly/2NC3J99', NOW(), 1, 1);
INSERT INTO ARTICLE (ARTICLE_TITLE, ARTICLE_TEXT, IMAGE_URL, DATE_ARTICLE_PUBLISHED, ARTICLE_PUBLISHED_BY_USER_ID, CATEGORY_CATEGORY_ID) VALUES ('Convallis aenean et tortor at risus viverra adipiscing faucibus in ornare', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa sapien faucibus et molestie ac feugiat. Accumsan lacus vel facilisis volutpat est velit egestas dui. At volutpat diam ut venenatis tellus. Turpis cursus in hac habitasse platea dictumst quisque sagittis purus. Sed vulputate mi sit amet mauris commodo quis. Pharetra sit amet aliquam id. Commodo odio aenean sed adipiscing. Ornare quam viverra orci sagittis eu. Elementum nisi quis eleifend quam adipiscing vitae. Nulla pellentesque dignissim enim sit amet venenatis urna. Duis convallis convallis tellus id interdum velit laoreet id. Tempor orci dapibus ultrices in. Bibendum at varius vel pharetra vel turpis nunc eget lorem. Et ligula ullamcorper malesuada proin. Sed libero enim sed faucibus turpis. Diam in arcu cursus euismod quis viverra. Vulputate ut pharetra sit amet. Lectus sit amet est placerat in. At augue eget arcu dictum varius duis at.

Ipsum consequat nisl vel pretium lectus quam. Netus et malesuada fames ac turpis egestas sed tempus. Rhoncus dolor purus non enim praesent elementum facilisis leo. Feugiat in ante metus dictum at tempor commodo ullamcorper. Nec tincidunt praesent semper feugiat nibh sed pulvinar. Consectetur lorem donec massa sapien faucibus et molestie. Consequat semper viverra nam libero justo laoreet sit amet. Diam in arcu cursus euismod quis viverra. Orci dapibus ultrices in iaculis nunc sed augue lacus. Ipsum dolor sit amet consectetur adipiscing elit. Dui faucibus in ornare quam. At auctor urna nunc id. Diam in arcu cursus euismod quis. Orci sagittis eu volutpat odio facilisis mauris sit amet massa. Orci dapibus ultrices in iaculis nunc sed augue lacus viverra. Eu turpis egestas pretium aenean pharetra. Aliquam id diam maecenas ultricies mi.

Sollicitudin ac orci phasellus egestas tellus rutrum tellus pellentesque. Et netus et malesuada fames. Augue interdum velit euismod in pellentesque. Nisl tincidunt eget nullam non nisi est sit amet. Ultrices sagittis orci a scelerisque purus semper eget duis. Erat nam at lectus urna duis convallis convallis. Amet aliquam id diam maecenas ultricies. Ac odio tempor orci dapibus ultrices in iaculis nunc. Facilisis mauris sit amet massa vitae tortor condimentum lacinia quis. Orci dapibus ultrices in iaculis. Id neque aliquam vestibulum morbi. Mauris rhoncus aenean vel elit scelerisque. Tortor id aliquet lectus proin nibh nisl condimentum id venenatis. Lorem sed risus ultricies tristique nulla aliquet enim tortor at. Ut aliquam purus sit amet. Sed faucibus turpis in eu mi bibendum neque egestas congue. Vel pharetra vel turpis nunc eget lorem dolor sed viverra.

Bibendum at varius vel pharetra vel. Ipsum a arcu cursus vitae. Pretium quam vulputate dignissim suspendisse in est. Lectus nulla at volutpat diam ut venenatis. Non enim praesent elementum facilisis. Sed euismod nisi porta lorem mollis aliquam. Amet tellus cras adipiscing enim eu turpis egestas. Consequat interdum varius sit amet mattis vulputate. Adipiscing tristique risus nec feugiat. Rhoncus urna neque viverra justo nec ultrices. Purus semper eget duis at. Elementum tempus egestas sed sed risus pretium quam vulputate. Quis commodo odio aenean sed adipiscing diam donec adipiscing. Quisque sagittis purus sit amet. Sagittis aliquam malesuada bibendum arcu vitae. Nisl suscipit adipiscing bibendum est. Quisque id diam vel quam elementum pulvinar etiam.

Tempus urna et pharetra pharetra massa massa ultricies mi quis. Aenean sed adipiscing diam donec adipiscing. Nibh nisl condimentum id venenatis a condimentum vitae sapien. Orci a scelerisque purus semper. Turpis egestas pretium aenean pharetra magna ac placerat. Bibendum enim facilisis gravida neque convallis. A scelerisque purus semper eget. Dolor sit amet consectetur adipiscing elit ut aliquam. Nisl pretium fusce id velit. Ac ut consequat semper viverra nam libero justo laoreet sit. Leo vel fringilla est ullamcorper eget. Faucibus nisl tincidunt eget nullam. Mattis nunc sed blandit libero volutpat. Aenean sed adipiscing diam donec adipiscing tristique. Lacus vel facilisis volutpat est velit egestas dui. Pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum. Amet justo donec enim diam vulputate ut pharetra sit. Convallis convallis tellus id interdum velit laoreet id.', 'https://bit.ly/2BHiSO3', NOW(), 1, 2);
INSERT INTO ARTICLE (ARTICLE_TITLE, ARTICLE_TEXT, IMAGE_URL, DATE_ARTICLE_PUBLISHED, ARTICLE_PUBLISHED_BY_USER_ID, CATEGORY_CATEGORY_ID) VALUES ('Leo duis ut diam quam nulla - in tellus integer feugiat scelerisque varius morbi enim nunc', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eget gravida cum sociis natoque penatibus et magnis. Etiam erat velit scelerisque in dictum non consectetur. Id ornare arcu odio ut sem nulla pharetra. Pellentesque habitant morbi tristique senectus et netus et. Scelerisque fermentum dui faucibus in ornare. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Sit amet tellus cras adipiscing enim eu turpis egestas. Ipsum dolor sit amet consectetur adipiscing elit. Ipsum dolor sit amet consectetur adipiscing. Praesent semper feugiat nibh sed pulvinar proin. Sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Luctus accumsan tortor posuere ac. Libero volutpat sed cras ornare arcu dui vivamus. Diam volutpat commodo sed egestas egestas fringilla phasellus.

Iaculis at erat pellentesque adipiscing commodo elit. Pretium lectus quam id leo in. Aenean euismod elementum nisi quis eleifend quam. At urna condimentum mattis pellentesque. Donec ultrices tincidunt arcu non sodales neque sodales ut. Egestas diam in arcu cursus euismod quis viverra nibh. Sem fringilla ut morbi tincidunt augue interdum velit. Tincidunt ornare massa eget egestas purus viverra. Scelerisque varius morbi enim nunc faucibus a pellentesque. Ipsum consequat nisl vel pretium lectus quam id leo. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit amet. Enim lobortis scelerisque fermentum dui faucibus. Habitant morbi tristique senectus et netus et malesuada fames ac. Enim facilisis gravida neque convallis a cras semper. Ornare suspendisse sed nisi lacus. Sed felis eget velit aliquet. Semper feugiat nibh sed pulvinar. Amet risus nullam eget felis eget nunc. Nunc non blandit massa enim. Sit amet consectetur adipiscing elit pellentesque habitant morbi.

Felis eget nunc lobortis mattis. Nunc faucibus a pellentesque sit amet porttitor. Eget duis at tellus at urna condimentum. Lorem ipsum dolor sit amet consectetur adipiscing elit duis. Purus sit amet luctus venenatis lectus magna. Diam phasellus vestibulum lorem sed risus. Ultricies tristique nulla aliquet enim. Viverra tellus in hac habitasse platea. Imperdiet dui accumsan sit amet. Diam maecenas sed enim ut. Malesuada fames ac turpis egestas maecenas pharetra. Amet tellus cras adipiscing enim eu turpis. Odio tempor orci dapibus ultrices in. Imperdiet dui accumsan sit amet nulla facilisi. Cum sociis natoque penatibus et. Tempor id eu nisl nunc mi ipsum. Id leo in vitae turpis massa sed elementum tempus.

Feugiat nibh sed pulvinar proin gravida. A erat nam at lectus urna duis convallis convallis. Semper feugiat nibh sed pulvinar. Vehicula ipsum a arcu cursus vitae congue. Nulla pharetra diam sit amet. Nam at lectus urna duis convallis convallis. Convallis posuere morbi leo urna molestie at elementum. Tortor consequat id porta nibh. Egestas pretium aenean pharetra magna ac placerat vestibulum. Ante in nibh mauris cursus mattis. Commodo nulla facilisi nullam vehicula ipsum a arcu. Eu non diam phasellus vestibulum. Eleifend donec pretium vulputate sapien nec sagittis aliquam. Tortor vitae purus faucibus ornare suspendisse sed nisi. Eget gravida cum sociis natoque penatibus et.', 'https://bit.ly/2S1evnP', NOW(), 1, 3);
INSERT INTO ARTICLE (ARTICLE_TITLE, ARTICLE_TEXT, IMAGE_URL, DATE_ARTICLE_PUBLISHED, ARTICLE_PUBLISHED_BY_USER_ID, CATEGORY_CATEGORY_ID) VALUES ('Ultrices vitae auctor eu augue ut lectus arcu bibendum at', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh venenatis cras sed felis eget velit aliquet sagittis id. Posuere ac ut consequat semper viverra nam. Posuere sollicitudin aliquam ultrices sagittis. Ut tortor pretium viverra suspendisse potenti nullam ac tortor. Egestas egestas fringilla phasellus faucibus scelerisque eleifend. Eu ultrices vitae auctor eu augue. Feugiat nibh sed pulvinar proin gravida. Cras fermentum odio eu feugiat pretium nibh ipsum. Donec adipiscing tristique risus nec. Habitasse platea dictumst vestibulum rhoncus est pellentesque. Tincidunt eget nullam non nisi est sit. In arcu cursus euismod quis. Dis parturient montes nascetur ridiculus mus mauris vitae. Risus feugiat in ante metus dictum at tempor commodo. Non nisi est sit amet facilisis magna. Habitant morbi tristique senectus et netus et malesuada fames. Ornare lectus sit amet est placerat in egestas.

Lectus nulla at volutpat diam ut venenatis tellus in. Facilisis leo vel fringilla est ullamcorper eget. Sit amet tellus cras adipiscing enim eu. Enim praesent elementum facilisis leo vel fringilla. Elit sed vulputate mi sit amet. Aliquam etiam erat velit scelerisque in dictum non consectetur a. Integer eget aliquet nibh praesent tristique magna. Ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae. Elementum nibh tellus molestie nunc non. Pellentesque massa placerat duis ultricies lacus sed turpis. Sodales ut eu sem integer vitae justo eget. Nibh tortor id aliquet lectus proin. Ut consequat semper viverra nam libero justo laoreet sit amet. Tristique senectus et netus et malesuada. Eget nulla facilisi etiam dignissim diam. Pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum. Arcu cursus euismod quis viverra nibh cras pulvinar mattis nunc.

Nulla at volutpat diam ut venenatis tellus in metus vulputate. Neque egestas congue quisque egestas diam in arcu cursus. Diam quis enim lobortis scelerisque fermentum dui faucibus in ornare. Erat velit scelerisque in dictum non consectetur. Eget nulla facilisi etiam dignissim diam quis enim lobortis. Non tellus orci ac auctor augue mauris augue. Laoreet id donec ultrices tincidunt. Massa sed elementum tempus egestas. Facilisis mauris sit amet massa vitae. Nunc vel risus commodo viverra maecenas accumsan lacus. Mi quis hendrerit dolor magna eget. Diam sollicitudin tempor id eu nisl nunc. Platea dictumst quisque sagittis purus sit. Tortor at auctor urna nunc id cursus metus aliquam eleifend.', 'https://bit.ly/2YDYuXr', NOW(), 1, 4);
INSERT INTO ARTICLE (ARTICLE_TITLE, ARTICLE_TEXT, IMAGE_URL, DATE_ARTICLE_PUBLISHED, ARTICLE_PUBLISHED_BY_USER_ID, CATEGORY_CATEGORY_ID) VALUES ('Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin - viverra ipsum?', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Purus faucibus ornare suspendisse sed nisi lacus. Rhoncus urna neque viverra justo nec ultrices dui. Tortor aliquam nulla facilisi cras. Eu ultrices vitae auctor eu augue ut lectus arcu. Justo laoreet sit amet cursus sit amet. Penatibus et magnis dis parturient montes nascetur ridiculus mus. Risus nec feugiat in fermentum. Leo duis ut diam quam nulla porttitor massa id. Dui ut ornare lectus sit amet est. Proin sed libero enim sed faucibus turpis in eu mi. Elementum sagittis vitae et leo duis ut diam quam. Donec enim diam vulputate ut pharetra. Tellus elementum sagittis vitae et. In dictum non consectetur a erat. Pulvinar elementum integer enim neque volutpat. Fermentum dui faucibus in ornare quam viverra orci sagittis.

Orci eu lobortis elementum nibh tellus molestie nunc. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Mauris commodo quis imperdiet massa. Vitae suscipit tellus mauris a diam maecenas sed enim ut. Id cursus metus aliquam eleifend mi in. Quis viverra nibh cras pulvinar mattis nunc sed blandit libero. Dictumst quisque sagittis purus sit amet volutpat consequat mauris. Elementum tempus egestas sed sed risus. At imperdiet dui accumsan sit amet nulla. Morbi tempus iaculis urna id volutpat lacus. Quam id leo in vitae turpis massa sed elementum tempus. Nisl rhoncus mattis rhoncus urna neque viverra.

Dolor morbi non arcu risus quis varius. Enim nulla aliquet porttitor lacus luctus accumsan tortor. Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Ut tortor pretium viverra suspendisse. Faucibus turpis in eu mi. Rhoncus mattis rhoncus urna neque. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. In pellentesque massa placerat duis ultricies lacus sed. Nibh tortor id aliquet lectus proin nibh nisl. Fusce id velit ut tortor pretium viverra suspendisse. Cras tincidunt lobortis feugiat vivamus at augue eget. Sem nulla pharetra diam sit. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Adipiscing at in tellus integer feugiat scelerisque varius morbi. Nec sagittis aliquam malesuada bibendum arcu vitae elementum. Bibendum est ultricies integer quis auctor elit. Quam quisque id diam vel quam elementum pulvinar. Gravida quis blandit turpis cursus in. Vestibulum morbi blandit cursus risus at ultrices. Facilisis gravida neque convallis a.

Augue mauris augue neque gravida. Faucibus interdum posuere lorem ipsum. Aliquet sagittis id consectetur purus ut. Id porta nibh venenatis cras sed felis eget velit aliquet. Ultricies lacus sed turpis tincidunt id aliquet risus. Urna nunc id cursus metus aliquam eleifend mi in nulla. Scelerisque felis imperdiet proin fermentum leo. Aliquet nibh praesent tristique magna sit amet purus gravida. Massa sed elementum tempus egestas sed. Sodales ut etiam sit amet nisl purus. Neque volutpat ac tincidunt vitae. Dictum sit amet justo donec enim diam.', 'https://bit.ly/2G16Lxl', NOW(), 1, 2);
INSERT INTO ARTICLE (ARTICLE_TITLE, ARTICLE_TEXT, IMAGE_URL, DATE_ARTICLE_PUBLISHED, ARTICLE_PUBLISHED_BY_USER_ID, CATEGORY_CATEGORY_ID) VALUES ('Pulvinar proin gravida hendrerit lectus a', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam faucibus purus in massa. Ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Lacus vestibulum sed arcu non. Placerat vestibulum lectus mauris ultrices eros in cursus. Semper auctor neque vitae tempus quam pellentesque nec. Amet tellus cras adipiscing enim. Urna id volutpat lacus laoreet non curabitur gravida arcu ac. Iaculis urna id volutpat lacus laoreet non. Amet massa vitae tortor condimentum lacinia quis vel. Massa eget egestas purus viverra accumsan in nisl nisi. Nisi lacus sed viverra tellus in hac habitasse platea. Mauris sit amet massa vitae tortor condimentum lacinia quis. Eu mi bibendum neque egestas congue quisque egestas diam. Feugiat sed lectus vestibulum mattis ullamcorper velit sed.

At ultrices mi tempus imperdiet nulla malesuada. Lacus vestibulum sed arcu non odio euismod. Pellentesque dignissim enim sit amet venenatis urna cursus eget. Sed faucibus turpis in eu mi bibendum neque egestas congue. Aliquam id diam maecenas ultricies mi eget. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Amet massa vitae tortor condimentum. Massa massa ultricies mi quis hendrerit. Urna et pharetra pharetra massa massa. Non odio euismod lacinia at quis risus. Sagittis id consectetur purus ut faucibus pulvinar elementum. Gravida in fermentum et sollicitudin ac orci phasellus egestas tellus. Ut ornare lectus sit amet. Cursus mattis molestie a iaculis at erat pellentesque adipiscing commodo. Amet tellus cras adipiscing enim eu turpis egestas pretium. Rhoncus urna neque viverra justo nec ultrices. Arcu dui vivamus arcu felis bibendum ut tristique et egestas. Imperdiet nulla malesuada pellentesque elit eget gravida cum sociis.

Egestas congue quisque egestas diam in arcu cursus euismod quis. Sapien faucibus et molestie ac feugiat sed. Suspendisse interdum consectetur libero id faucibus nisl tincidunt. Quisque non tellus orci ac auctor. Sem nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Convallis tellus id interdum velit laoreet id. Id consectetur purus ut faucibus pulvinar elementum. Habitasse platea dictumst quisque sagittis purus. Sit amet massa vitae tortor condimentum lacinia quis. Eget mauris pharetra et ultrices neque ornare aenean euismod. Mi sit amet mauris commodo quis imperdiet massa tincidunt. Eu ultrices vitae auctor eu augue. Volutpat sed cras ornare arcu. Adipiscing elit pellentesque habitant morbi tristique senectus et netus. Urna nec tincidunt praesent semper. Tincidunt dui ut ornare lectus sit amet est. Netus et malesuada fames ac.

Sem nulla pharetra diam sit amet nisl suscipit. Dis parturient montes nascetur ridiculus mus mauris. Libero enim sed faucibus turpis in eu. Dui sapien eget mi proin sed libero. Magna fermentum iaculis eu non diam phasellus vestibulum lorem sed. Faucibus purus in massa tempor. Urna molestie at elementum eu facilisis sed. Vivamus at augue eget arcu dictum varius duis at consectetur. Adipiscing vitae proin sagittis nisl rhoncus. Sed adipiscing diam donec adipiscing tristique risus nec feugiat in. Proin sed libero enim sed faucibus turpis. Rutrum tellus pellentesque eu tincidunt tortor aliquam. Mauris in aliquam sem fringilla ut morbi tincidunt augue. Consectetur lorem donec massa sapien faucibus.

Libero volutpat sed cras ornare arcu. Ut aliquam purus sit amet luctus. Diam quam nulla porttitor massa id neque aliquam. Proin sed libero enim sed faucibus. Vivamus at augue eget arcu dictum varius duis at consectetur. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor. Pellentesque dignissim enim sit amet. Blandit volutpat maecenas volutpat blandit aliquam etiam erat velit. Suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Imperdiet nulla malesuada pellentesque elit. Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque sit. In arcu cursus euismod quis viverra nibh cras pulvinar. Et magnis dis parturient montes. Mattis aliquam faucibus purus in massa tempor. Nunc non blandit massa enim nec dui nunc. Vulputate sapien nec sagittis aliquam. Sit amet justo donec enim. Tellus at urna condimentum mattis pellentesque id nibh tortor. Netus et malesuada fames ac turpis egestas integer eget aliquet.', 'https://bit.ly/2XynBd0', NOW(), 1, 3);
INSERT INTO ARTICLE (ARTICLE_TITLE, ARTICLE_TEXT, IMAGE_URL, DATE_ARTICLE_PUBLISHED, ARTICLE_PUBLISHED_BY_USER_ID, CATEGORY_CATEGORY_ID) VALUES ('Neque aliquam vestibulum morbi blandit cursus', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Leo in vitae turpis massa sed elementum tempus. Pellentesque habitant morbi tristique senectus et. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar. Pretium vulputate sapien nec sagittis aliquam malesuada. Ornare massa eget egestas purus viverra accumsan in. At varius vel pharetra vel. Tortor at risus viverra adipiscing at in tellus integer feugiat. Sit amet cursus sit amet dictum. Sem nulla pharetra diam sit amet nisl suscipit adipiscing. Id consectetur purus ut faucibus. Imperdiet sed euismod nisi porta lorem mollis aliquam ut.

Suspendisse sed nisi lacus sed viverra tellus in hac. Pretium aenean pharetra magna ac placerat vestibulum. Pharetra convallis posuere morbi leo urna molestie. Fringilla est ullamcorper eget nulla facilisi etiam. Condimentum vitae sapien pellentesque habitant morbi tristique. Ac auctor augue mauris augue neque. Condimentum lacinia quis vel eros. Ullamcorper velit sed ullamcorper morbi. Cras adipiscing enim eu turpis egestas pretium aenean. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Sit amet nisl purus in mollis. Ultricies mi quis hendrerit dolor magna eget. Facilisi morbi tempus iaculis urna id volutpat. Viverra vitae congue eu consequat ac felis donec. In aliquam sem fringilla ut morbi tincidunt augue interdum. Faucibus interdum posuere lorem ipsum dolor sit. Ultrices gravida dictum fusce ut. Nisl tincidunt eget nullam non nisi est sit amet. Ut pharetra sit amet aliquam. Eget lorem dolor sed viverra.

Phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Suspendisse interdum consectetur libero id faucibus. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis. Tellus pellentesque eu tincidunt tortor aliquam. Vel eros donec ac odio tempor orci. Quisque non tellus orci ac auctor augue. Nunc faucibus a pellentesque sit amet porttitor eget. Neque laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Ac placerat vestibulum lectus mauris ultrices eros. Sit amet massa vitae tortor condimentum lacinia quis. Diam phasellus vestibulum lorem sed risus ultricies. Dignissim suspendisse in est ante in. Leo integer malesuada nunc vel risus commodo viverra. Quis lectus nulla at volutpat diam ut venenatis tellus. Tellus cras adipiscing enim eu turpis egestas. Purus in mollis nunc sed. Id semper risus in hendrerit gravida. Vulputate mi sit amet mauris commodo quis. Viverra mauris in aliquam sem fringilla ut.', 'https://bit.ly/2NCtuGa', NOW(), 1, 4);
INSERT INTO ARTICLE (ARTICLE_TITLE, ARTICLE_TEXT, IMAGE_URL, DATE_ARTICLE_PUBLISHED, ARTICLE_PUBLISHED_BY_USER_ID, CATEGORY_CATEGORY_ID) VALUES ('Habitant morbi tristique senectus et netus. Id diam vel quam elementum?', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Imperdiet dui accumsan sit amet nulla. Iaculis urna id volutpat lacus. Turpis egestas integer eget aliquet nibh praesent. Sit amet consectetur adipiscing elit. Feugiat nisl pretium fusce id velit ut tortor pretium viverra. Cursus in hac habitasse platea. Aliquam malesuada bibendum arcu vitae elementum curabitur. Urna condimentum mattis pellentesque id nibh tortor id aliquet lectus. Gravida neque convallis a cras semper auctor neque vitae. Arcu vitae elementum curabitur vitae. Eget nulla facilisi etiam dignissim diam quis enim lobortis scelerisque. Risus in hendrerit gravida rutrum quisque. Urna et pharetra pharetra massa massa ultricies mi quis hendrerit. Purus non enim praesent elementum facilisis leo. In pellentesque massa placerat duis ultricies lacus sed turpis. Eros donec ac odio tempor. Id diam maecenas ultricies mi eget. Id velit ut tortor pretium viverra suspendisse potenti nullam.

Arcu bibendum at varius vel pharetra vel. Nisi scelerisque eu ultrices vitae auctor eu augue ut lectus. Ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at augue. Placerat duis ultricies lacus sed turpis tincidunt id. Sed euismod nisi porta lorem mollis aliquam ut porttitor leo. Iaculis nunc sed augue lacus viverra vitae congue eu. Tristique et egestas quis ipsum suspendisse ultrices gravida. Vel pretium lectus quam id leo. Tellus elementum sagittis vitae et. Nunc congue nisi vitae suscipit tellus.

Non enim praesent elementum facilisis. Aliquet eget sit amet tellus cras adipiscing enim eu turpis. Ornare arcu dui vivamus arcu felis bibendum. Ac tortor vitae purus faucibus ornare suspendisse. Pellentesque massa placerat duis ultricies lacus sed. Odio ut sem nulla pharetra diam sit amet nisl. Tristique senectus et netus et malesuada fames ac. Amet porttitor eget dolor morbi. Facilisis mauris sit amet massa vitae tortor condimentum lacinia. Porttitor rhoncus dolor purus non. Tellus integer feugiat scelerisque varius morbi. Sollicitudin nibh sit amet commodo nulla facilisi. Eu nisl nunc mi ipsum faucibus vitae aliquet nec. Sem nulla pharetra diam sit amet nisl suscipit.

Sit amet risus nullam eget felis eget nunc. Posuere lorem ipsum dolor sit amet consectetur adipiscing. Et molestie ac feugiat sed. Maecenas sed enim ut sem viverra. Pharetra magna ac placerat vestibulum lectus mauris. Hendrerit dolor magna eget est lorem ipsum dolor. Nec feugiat nisl pretium fusce id velit ut tortor pretium. Turpis nunc eget lorem dolor sed viverra ipsum nunc. Mattis ullamcorper velit sed ullamcorper. Praesent tristique magna sit amet purus gravida quis blandit turpis. Viverra justo nec ultrices dui sapien. Lacus suspendisse faucibus interdum posuere lorem ipsum. Cras semper auctor neque vitae tempus quam pellentesque. Integer feugiat scelerisque varius morbi enim nunc faucibus a. Dis parturient montes nascetur ridiculus mus mauris. Interdum consectetur libero id faucibus nisl tincidunt.', 'https://bit.ly/30k3QaW', NOW(), 1, 2);
INSERT INTO ARTICLE (ARTICLE_TITLE, ARTICLE_TEXT, IMAGE_URL, DATE_ARTICLE_PUBLISHED, ARTICLE_PUBLISHED_BY_USER_ID, CATEGORY_CATEGORY_ID) VALUES ('Massa vitae tortor condimentum lacinia quis vel eros donec ac - ellus in metus vulputate eu', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eget magna fermentum iaculis eu non diam phasellus. Et ligula ullamcorper malesuada proin libero nunc consequat interdum. Tincidunt eget nullam non nisi est sit amet facilisis. Id leo in vitae turpis massa sed elementum tempus egestas. Feugiat scelerisque varius morbi enim nunc faucibus. Lectus vestibulum mattis ullamcorper velit sed ullamcorper. Elementum integer enim neque volutpat ac. Nec tincidunt praesent semper feugiat nibh. Consectetur a erat nam at. Diam ut venenatis tellus in. Malesuada nunc vel risus commodo. Egestas diam in arcu cursus euismod quis viverra nibh cras. Quam nulla porttitor massa id neque aliquam vestibulum morbi blandit. Sem et tortor consequat id porta. Purus in massa tempor nec feugiat nisl pretium. At ultrices mi tempus imperdiet nulla malesuada pellentesque elit. Turpis nunc eget lorem dolor. Habitant morbi tristique senectus et netus et malesuada.

Bibendum ut tristique et egestas. Aenean sed adipiscing diam donec. Sit amet est placerat in egestas erat imperdiet. Lobortis mattis aliquam faucibus purus in massa tempor nec. Feugiat pretium nibh ipsum consequat nisl vel pretium. Magnis dis parturient montes nascetur. Tellus elementum sagittis vitae et leo duis ut diam quam. Sit amet nulla facilisi morbi tempus iaculis urna. Porttitor massa id neque aliquam. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices. Aliquam sem et tortor consequat id porta nibh.

Aliquam sem et tortor consequat id porta nibh. Elit sed vulputate mi sit amet mauris commodo. Amet mauris commodo quis imperdiet massa tincidunt nunc. Libero id faucibus nisl tincidunt eget nullam non nisi. Porta non pulvinar neque laoreet suspendisse interdum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Lectus sit amet est placerat in egestas erat imperdiet sed. Semper risus in hendrerit gravida. Convallis posuere morbi leo urna molestie at elementum. Faucibus nisl tincidunt eget nullam non nisi. Urna cursus eget nunc scelerisque viverra mauris in. Sit amet risus nullam eget felis eget. Ac felis donec et odio pellentesque. Tellus in hac habitasse platea.

Ullamcorper a lacus vestibulum sed. Tempus quam pellentesque nec nam aliquam sem et tortor consequat. Consectetur libero id faucibus nisl tincidunt eget nullam. Risus viverra adipiscing at in tellus. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Nulla aliquet porttitor lacus luctus accumsan tortor posuere ac. Lectus sit amet est placerat. Blandit turpis cursus in hac habitasse. Eget mauris pharetra et ultrices. Sapien et ligula ullamcorper malesuada proin. Sagittis vitae et leo duis ut diam. Accumsan tortor posuere ac ut consequat semper viverra nam libero. Velit dignissim sodales ut eu sem integer. Volutpat sed cras ornare arcu dui vivamus arcu felis bibendum. Convallis a cras semper auctor neque. Dolor sit amet consectetur adipiscing.

Sit amet venenatis urna cursus eget nunc scelerisque. Eget mi proin sed libero enim sed. Nullam vehicula ipsum a arcu cursus. Quis blandit turpis cursus in hac. Phasellus egestas tellus rutrum tellus. Commodo viverra maecenas accumsan lacus vel. Nulla malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Ut morbi tincidunt augue interdum. Neque vitae tempus quam pellentesque nec nam aliquam sem. Habitasse platea dictumst quisque sagittis purus sit amet volutpat. Purus non enim praesent elementum. Massa massa ultricies mi quis hendrerit dolor magna. Mi bibendum neque egestas congue. Massa vitae tortor condimentum lacinia quis vel eros donec. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Morbi tristique senectus et netus et malesuada.

Enim nunc faucibus a pellentesque sit amet porttitor eget dolor. Amet est placerat in egestas erat imperdiet. Ut diam quam nulla porttitor. Consectetur adipiscing elit ut aliquam purus sit amet luctus. Sed vulputate mi sit amet. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Tincidunt vitae semper quis lectus. Sed odio morbi quis commodo odio aenean sed adipiscing. Quam quisque id diam vel quam elementum pulvinar etiam. Accumsan sit amet nulla facilisi morbi tempus. Sagittis aliquam malesuada bibendum arcu. Viverra nibh cras pulvinar mattis nunc sed. Facilisis sed odio morbi quis commodo odio aenean sed. Potenti nullam ac tortor vitae purus faucibus.', 'https://bit.ly/32f3ljV', NOW(), 1, 2);
INSERT INTO ARTICLE (ARTICLE_TITLE, ARTICLE_TEXT, IMAGE_URL, DATE_ARTICLE_PUBLISHED, ARTICLE_PUBLISHED_BY_USER_ID, CATEGORY_CATEGORY_ID) VALUES ('Eleifend quam adipiscing vitae proin sagittis nisl rhoncus!', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Massa vitae tortor condimentum lacinia quis vel eros donec ac. Tellus in metus vulputate eu scelerisque felis imperdiet. Mattis molestie a iaculis at. Tincidunt dui ut ornare lectus sit. Orci nulla pellentesque dignissim enim sit amet. Dignissim cras tincidunt lobortis feugiat vivamus at augue. Iaculis eu non diam phasellus vestibulum lorem sed risus ultricies. Eleifend quam adipiscing vitae proin sagittis nisl rhoncus. Neque aliquam vestibulum morbi blandit cursus. Donec enim diam vulputate ut pharetra sit amet aliquam id. Velit scelerisque in dictum non consectetur a. Dictum sit amet justo donec enim diam vulputate ut. Lectus arcu bibendum at varius vel. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Viverra nibh cras pulvinar mattis nunc sed blandit libero. Pretium fusce id velit ut tortor pretium viverra suspendisse potenti. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque.

Commodo ullamcorper a lacus vestibulum sed. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Ac placerat vestibulum lectus mauris ultrices eros. Habitant morbi tristique senectus et netus. Id diam vel quam elementum pulvinar etiam non. Vestibulum mattis ullamcorper velit sed ullamcorper morbi. Sagittis purus sit amet volutpat consequat mauris nunc. Pulvinar proin gravida hendrerit lectus a. Netus et malesuada fames ac turpis egestas. Non pulvinar neque laoreet suspendisse interdum consectetur libero. Gravida in fermentum et sollicitudin ac. Porttitor lacus luctus accumsan tortor posuere ac ut consequat semper. Lacus sed turpis tincidunt id aliquet risus feugiat in ante. Nunc faucibus a pellentesque sit amet porttitor eget dolor. Cursus in hac habitasse platea dictumst.

Ut sem viverra aliquet eget sit amet tellus cras adipiscing. Nisi est sit amet facilisis magna. In est ante in nibh mauris cursus mattis molestie a. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Viverra ipsum nunc aliquet bibendum enim facilisis. Et ultrices neque ornare aenean euismod elementum. Amet est placerat in egestas erat imperdiet sed euismod nisi. Maecenas sed enim ut sem viverra. Sit amet tellus cras adipiscing enim eu turpis. Feugiat in fermentum posuere urna nec tincidunt. Amet dictum sit amet justo donec enim. Eros in cursus turpis massa tincidunt dui ut ornare lectus. Metus vulputate eu scelerisque felis imperdiet proin. Massa enim nec dui nunc mattis. Ut consequat semper viverra nam libero justo laoreet sit. Diam in arcu cursus euismod quis viverra nibh. Amet porttitor eget dolor morbi non.

Proin sed libero enim sed faucibus. Id venenatis a condimentum vitae sapien pellentesque habitant morbi. Purus faucibus ornare suspendisse sed nisi lacus sed. Erat velit scelerisque in dictum non. Ut consequat semper viverra nam libero justo laoreet sit. Elementum sagittis vitae et leo. Ut sem nulla pharetra diam. Cras semper auctor neque vitae tempus quam pellentesque. Ultrices vitae auctor eu augue ut lectus arcu bibendum at. Cursus euismod quis viverra nibh cras pulvinar mattis nunc. Velit laoreet id donec ultrices tincidunt arcu non sodales neque.

Sit amet volutpat consequat mauris nunc congue nisi. Nulla pharetra diam sit amet nisl suscipit adipiscing bibendum. Arcu non sodales neque sodales ut etiam sit amet nisl. Leo duis ut diam quam nulla. In tellus integer feugiat scelerisque varius morbi enim nunc. Sed id semper risus in hendrerit. Quam id leo in vitae turpis. Aenean sed adipiscing diam donec adipiscing tristique. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Convallis aenean et tortor at risus viverra adipiscing. Faucibus in ornare quam viverra. Leo urna molestie at elementum eu facilisis sed odio. Fames ac turpis egestas sed tempus!', 'https://bit.ly/2Xxgkz3', NOW(), 1, 3);