INSERT INTO COMMENT (COMMENT_TEXT, DATE_COMMENT_PUBLISHED, ARTICLE_ARTICLE_ID, COMMENT_PUBLISHED_BY_USER_ID) VALUES ("Some sample comment", NOW(), 1, 2);
INSERT INTO COMMENT (COMMENT_TEXT, DATE_COMMENT_PUBLISHED, ARTICLE_ARTICLE_ID, COMMENT_PUBLISHED_BY_USER_ID) VALUES ("Another sample comment", NOW(), 2, 3);
