INSERT INTO TAG (TAG_NAME) VALUES ('Depression');
INSERT INTO TAG (TAG_NAME) VALUES ('Anxiety');
INSERT INTO TAG (TAG_NAME) VALUES ('Phobias');
INSERT INTO TAG (TAG_NAME) VALUES ('Psychotherapy');
INSERT INTO TAG (TAG_NAME) VALUES ('Mindfulness');
INSERT INTO TAG (TAG_NAME) VALUES ('Religion');
INSERT INTO TAG (TAG_NAME) VALUES ('Supernatural');
INSERT INTO TAG (TAG_NAME) VALUES ('Healing');
INSERT INTO TAG (TAG_NAME) VALUES ('Eastern Practices');
INSERT INTO TAG (TAG_NAME) VALUES ('Motivation');
INSERT INTO TAG (TAG_NAME) VALUES ('Relationships');
INSERT INTO TAG (TAG_NAME) VALUES ('Positive Thinking');
INSERT INTO TAG (TAG_NAME) VALUES ('Emotions');
INSERT INTO TAG (TAG_NAME) VALUES ('Self-Help');
INSERT INTO TAG (TAG_NAME) VALUES ('Time Management');
INSERT INTO TAG (TAG_NAME) VALUES ('Learning From Experience');
INSERT INTO TAG (TAG_NAME) VALUES ('Personal Development Methods');

